import "./globals.css";
import { Poppins } from "next/font/google";
import Provider from "@/components/Provider";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "300", "400", "600", "700", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
